#!/bin/bash
# Deploy Dagggerfall Unity and mods

# Stop if anything goes wrong
set -e

self=$(basename "$0")
version="1.2"

fatal() {
    echo "$self: $1" 1>&2
    exit 1
}

usage() {
    echo "Usage: $self [-f <config file>] <target_directory>" 1>&2
    exit 1
}

owndir=$(dirname "$0")
owndir=$(cd "$owndir" && pwd)
[ -z "$owndir" ] && fatal "can't find my own directory"

# Set defaults
SOURCEDIR="$owndir"

configfile=~/".${self}rc"

if [ "$1" = "-f" ]; then
    configfile="$2"
    shift 2
fi
[[ "$1" = "-h" || "$1" = "--help" ]] && usage

[ -n "$1" ] || usage
TARGETDIR="$1"

TEMP=$(mktemp -d)
[ -d "$TEMP" ] || fatal "Couldn't create a private temp directory"
trap "rm -rf $TEMP" EXIT

[ -e "$configfile" ] || fatal "Can't file configuration file \`$configfile'; Please use sample.${self}rc as a template"

source "$configfile"

# -- Archive names

# Base game https://www.dfworkshop.net/projects/daggerfall-unity/live-builds/
case "$BASEGAME" in
    STABLE)
        ARC_BASEGAME=interkarma-daggerfall-unity-daggerfallunity_linux_universal-148.zip
        ;;
    PREALPHA)
        ARC_BASEGAME=interkarma-daggerfall-unity-daggerfallunity_linux_universal-149.zip
        ;;
    DEV)
        # zip containing everything below "build" subdirectory
        ARC_BASEGAME=daggerfall-unity_linux64-dev.zip
        ;;
    *)
        fatal "BASEGAME should be one of STABLE, PREALPHA or DEV"
esac

# Mods https://forums.dfworkshop.net/viewforum.php?f=27

# Daggerfall Remaster 3.0 https://forums.dfworkshop.net/viewtopic.php?f=27&t=1168
ARC_REMASTER30=Textures_3.0.rar

# D.R.E.A.M. https://forums.dfworkshop.net/viewtopic.php?f=27&t=1168
ARC_DREAM='DREAM Linux.rar'

# Daggerfall Textures XL https://forums.dfworkshop.net/viewtopic.php?f=27&t=1176
ARC_TEXTURESXL=Textures.zip

# TOPAZ AI Textures https://forums.dfworkshop.net/viewtopic.php?f=14&t=1642
ARC_TOPAZTEXTURES=TexturesFreak2121.7z

# Trees of Daggerfall https://forums.dfworkshop.net/viewtopic.php?f=22&t=1826
ARC_TREESOFDAGGERFALL="Trees Of Daggerfall 0.8b.zip"

# Bright Exit https://forums.dfworkshop.net/viewtopic.php?f=27&t=1168&start=100#p16197
ARC_BRIGHTEXIT=095_0-0_Emission.png

# Discrete Crosshair https://forums.dfworkshop.net/viewtopic.php?f=27&t=1650
ARC_DISCRETECROSSHAIR=Crosshair.png

# Charcoal Ghosts https://forums.dfworkshop.net/viewtopic.php?f=27&t=1526
ARC_CHARCOALGHOSTS=CharcoalGhosts1.1.zip

# Daggerfont https://forums.dfworkshop.net/viewtopic.php?f=14&t=1538&start=20#p18342
ARC_DAGGERFONT=FONT0003-SDF.zip

# Handpainted Models https://forums.dfworkshop.net/viewtopic.php?f=27&t=583
ARC_HANDPAINTEDMODELS="Handpainted v150.zip"

# Fancy Indicators https://forums.dfworkshop.net/viewtopic.php?f=22&t=1671
ARC_FANCYINDICATORS=FancyVitalIndicators.zip

# Compass texture https://forums.dfworkshop.net/viewtopic.php?f=14&t=630
ARC_COMPASSTEXTURES=CompassTextures.7z

# Recreated Travel map https://forums.dfworkshop.net/viewtopic.php?f=22&t=1804&p=21721#p21721
ARC_RECREATEDTRAVELMAP=TRAV0I00.IMG.png

# Enhanced Sky https://forums.dfworkshop.net/viewtopic.php?f=27&t=1542
ARC_ENHANCEDSKY=EnhancedSky_2.1.1.zip

# Distant Terrain https://forums.dfworkshop.net/viewtopic.php?f=27&t=10
ARC_DISTANTTERRAIN=DistantTerrain_2.6.0.zip

# Real Grass 2 https://forums.dfworkshop.net/viewtopic.php?f=27&t=964
ARC_REALGRASS=RealGrass_2.4.zip

# Harvestable Crops https://forums.dfworkshop.net/viewtopic.php?f=27&t=964
ARC_HARVESTABLECROPS=HarvestableCrops_v0.2_.7z

# Vibrant Wind https://forums.dfworkshop.net/viewtopic.php?f=14&t=532
ARC_VIBRANTWIND=VibrantWind_v0.5_.7z

# Realtime Reflections https://forums.dfworkshop.net/viewtopic.php?f=27&t=122
ARC_REALTIMEREFLECTIONS=RealtimeReflections_2.2.2.zip

# Villager Immersion Overhaul https://forums.dfworkshop.net/viewtopic.php?f=27&t=924
ARC_VILLAGERIMMERSION=VIO-V2.rar

# Post Processing Effects https://forums.dfworkshop.net/viewtopic.php?f=27&t=694
ARC_POSTPROCESSING=PostProcessing_1.0.1.zip

# Convenient Clock https://forums.dfworkshop.net/viewtopic.php?f=27&t=1021
ARC_CONVENIENTCLOCK="Convenient Clock 1.02.zip"

# Loading Screen https://forums.dfworkshop.net/viewtopic.php?f=27&t=469
ARC_LOADINGSCREEN=LoadingScreen_2.2.1.zip
ARC_LOADINGSCREENOBLIVION=OblivionStyledLoadScreensV2.rar

# Readable books https://forums.dfworkshop.net/viewtopic.php?f=14&t=1607
ARC_READABLEBOOKS=books.zip

# Soundscape by MidnightPrince inspired by "Music To Travel By" by Helegad https://forums.dfworkshop.net/viewtopic.php?f=14&t=1347&p=16078#p16078
# Renamed from Sound.zip
ARC_MIDNIGHTPRINCESOUNDSCAPE=Soundscape_MidnightPrince.zip

# Daggerfall Remastered Music Project https://forums.dfworkshop.net/viewtopic.php?f=22&t=921&start=70
ARC_DFREMASTEREDMUSIC=DaggerfallMusicRemasteredFinal.rar

# Cleaned SoundClips https://forums.dfworkshop.net/viewtopic.php?f=14&t=1692
ARC_SOUNDCLIPSMIXDOWN=SoundClips-1.3.zip

# Tedious Travel https://forums.dfworkshop.net/viewtopic.php?f=22&t=1293
ARC_TEDIOUSTRAVEL=TediousTravel-0.3.0.zip

# Warm Ashes: Dangerous Dungeon Exteriors https://forums.dfworkshop.net/viewtopic.php?f=27&t=1087
ARC_WARMASHES=FixedWarmAshes.zip
# https://forums.dfworkshop.net/viewtopic.php?f=27&t=1087&start=60#p21196
WARMASHES_QUESTLIST=QuestList-WarmAshes.txt.zip

# DFU Quest Pack #1 https://forums.dfworkshop.net/viewtopic.php?f=27&t=924
ARC_QUESTPACK1=Quest_Pack_1.zip
ARC_QUESTPACK1PERPETUALS="Quest Pack 1 Perpetuals.zip"

# Archeologists guild https://forums.dfworkshop.net/viewtopic.php?f=27&t=888&hilit=archeologists&start=80
ARC_ARCHEOLOGISTSGUILD=ArchaeologistsGuild-0.5.zip

# Persistent Dungeons https://forums.dfworkshop.net/viewtopic.php?f=27&t=1667
ARC_PERSISTENTDUNGEONS='persistent dungeons.dfmod'

# -- preflight checks

check_available() {
    command -v "$1" > /dev/null 2>&1 || fatal "\`$1' command not found"
}

# Use 7z for everything?
check_available unzip
check_available unrar
check_available 7z

missing_options=()
for archive in ${!ARC_*}; do
    option="${archive#ARC_}"
    if [ "${!option}" ]; then
	if [ "${!option}" != "N" ]; then
	    echo "Testing \`${!archive}' presence..."
	    [ -e "$SOURCEDIR/${!archive}" ] || fatal "archive \`$SOURCEDIR/${!archive}' not found, aborting"
	fi
    else
	missing_options+=("$option")
    fi
done
[ ${#missing_options} -gt 0 ] && fatal "Your configuration file is missing options: ${missing_options[*]}"

check_conflicting() {
    local reason=$1
    shift
    local conflicting=()
    for option in "$@"; do
        [ "${!option}" = "Y" ] && conflicting+=("$option")
    done
    [ ${#conflicting[*]} -gt 1 ] && fatal "You selected conflicting options ($reason): ${conflicting[*]}"
    return 0
}

# Textures
# Not TOPAZTEXTURES here since it's not a full overhaul
check_conflicting "Texture overhauls" DREAM REMASTER30 TEXTURESXL

check_conflicting "DREAM contains CharcoalGhosts"  DREAM CHARCOALGHOSTS
check_conflicting "DREAM contains BrightExit"  DREAM BRIGHTEXIT

# Songs
check_conflicting "Songs overhauls" MIDNIGHTPRINCESOUNDSCAPE DFREMASTEREDMUSIC

# -- Let's go

SIGNATUREFILE="$TARGETDIR/.deploy_DFU.log"
if [ -d "$TARGETDIR" ]; then
    [ -e "$SIGNATUREFILE" ] || fatal "not replacing \`$TARGETDIR' we didn't create"
    rm -rf "$TARGETDIR"
fi
mkdir -p "$TARGETDIR"
echo "Install script: $self $version" > "$SIGNATUREFILE"

unzip "$SOURCEDIR/$ARC_BASEGAME" -d "$TARGETDIR"
echo "Base game: $ARC_BASEGAME ($BASEGAME)" >> "$SIGNATUREFILE"
echo "Options: USE_HACKS=$USE_HACKS" >> "$SIGNATUREFILE"
assets="$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets

# -- Eye candy

if [ "$DREAM" = "Y" ]; then
    unrar x "$SOURCEDIR/$ARC_DREAM" "$assets"/Mods/
    echo "Mod: $ARC_DREAM" >> "$SIGNATUREFILE"
fi

if [ "$REMASTER30" = "Y" ]; then
    unrar x "$SOURCEDIR/$ARC_REMASTER30" "$assets"/
    echo "Mod: $ARC_REMASTER30" >> "$SIGNATUREFILE"
fi

if [ "$TEXTURESXL" = "Y" ]; then
    unzip -o "$SOURCEDIR/$ARC_TEXTURESXL" -d "$assets"/
    echo "Mod: $ARC_TEXTURESXL" >> "$SIGNATUREFILE"
fi

if [ "$TOPAZTEXTURES" = "Y" ]; then
    7z x "$SOURCEDIR/$ARC_TOPAZTEXTURES" -o"$assets"/ -aoa
    echo "Mod: $ARC_TOPAZTEXTURES" >> "$SIGNATUREFILE"
fi

if [ "$TREESOFDAGGERFALL" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_TREESOFDAGGERFALL" -d "$assets"/Mods "StandaloneLinux/trees of daggerfall.dfmod"
    echo "Mod: $ARC_TREESOFDAGGERFALL" >> "$SIGNATUREFILE"
fi

if [ "$BRIGHTEXIT" = "Y" ]; then
    cp "$SOURCEDIR/$ARC_BRIGHTEXIT" "$assets"/Textures/
    echo "Mod: $ARC_BRIGHTEXIT" >> "$SIGNATUREFILE"
fi

if [ "$DISCRETECROSSHAIR" = "Y" ]; then
    cp "$SOURCEDIR/$ARC_DISCRETECROSSHAIR" "$assets"/Textures/
    echo "Mod: $ARC_DISCRETECROSSHAIR" >> "$SIGNATUREFILE"
fi

if [ "$CHARCOALGHOSTS" = "Y" ]; then
    unzip -o "$SOURCEDIR/$ARC_CHARCOALGHOSTS" -d "$assets"/Textures/
    echo "Mod: $ARC_CHARCOALGHOSTS" >> "$SIGNATUREFILE"
fi

if [ "$DAGGERFONT" = "Y" ]; then
    unzip -o "$SOURCEDIR/$ARC_DAGGERFONT" -d "$assets"/Fonts/
    echo "Mod: $ARC_DAGGERFONT" >> "$SIGNATUREFILE"
fi

if [ "$HANDPAINTEDMODELS" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_HANDPAINTEDMODELS" -d "$assets"/Mods "${ARC_HANDPAINTEDMODELS%.zip}/StandaloneLinux/*.dfmod"
    echo "Mod: $ARC_HANDPAINTEDMODELS" >> "$SIGNATUREFILE"
fi

if [ "$FANCYINDICATORS" = "Y" ]; then
    unzip -o "$SOURCEDIR/$ARC_FANCYINDICATORS" -d "$assets"/
    echo "Mod: $ARC_FANCYINDICATORS" >> "$SIGNATUREFILE"
fi

if [ "$COMPASSTEXTURES" = "Y" ]; then
    7z e "$SOURCEDIR/$ARC_COMPASSTEXTURES" "[MOD] CompassTextures/$COMPASSTEXTURE/*" -o"$assets"/Textures/Img/ -aoa
    # Those compasses have standard size
    for compassfile in "$assets"/Textures/Img/COMP{ASS,BOX}.IMG.xml; do
	[ -e "$compassfile" ] && mv "$compassfile" "$compassfile.disabled"
    done
    echo "Mod: $ARC_COMPASSTEXTURES ($COMPASSTEXTURE)" >> "$SIGNATUREFILE"
fi

if [ "$RECREATEDTRAVELMAP" = "Y" ]; then
    cp "$SOURCEDIR/$ARC_RECREATEDTRAVELMAP" "$assets"/Textures/Img/
    echo "Mod: $ARC_RECREATEDTRAVELMAP" >> "$SIGNATUREFILE"
fi

if [ "$ENHANCEDSKY" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_ENHANCEDSKY" -d "$assets"/Mods "StandaloneLinux/enhanced sky.dfmod"
    echo "Mod: $ARC_ENHANCEDSKY" >> "$SIGNATUREFILE"
fi

if [ "$DISTANTTERRAIN" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_DISTANTTERRAIN" -d "$assets"/Mods "StandaloneLinux/distant terrain.dfmod"
    echo "Mod: $ARC_DISTANTTERRAIN" >> "$SIGNATUREFILE"
fi

if [ "$REALGRASS" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_REALGRASS" "${ARC_REALGRASS%.zip}"/Mod/Linux/realgrass.dfmod -d "$assets"/Mods/
    echo "Mod: $ARC_REALGRASS" >> "$SIGNATUREFILE"
fi

if [ "$HARVESTABLECROPS" = "Y" ]; then
    7z e "$SOURCEDIR/$ARC_HARVESTABLECROPS" "${ARC_HARVESTABLECROPS%.7z}"/Linux/harvestablecrops.dfmod -o"$assets"/Mods/
    echo "Mod: $ARC_HARVESTABLECROPS" >> "$SIGNATUREFILE"
fi

if [ "$VIBRANTWIND" = "Y" ]; then
    7z e "$SOURCEDIR/$ARC_VIBRANTWIND" "${ARC_VIBRANTWIND%.7z}"/Linux/vibrantwind.dfmod -o"$assets"/Mods/
    echo "Mod: $ARC_VIBRANTWIND" >> "$SIGNATUREFILE"
fi

if [ "$REALTIMEREFLECTIONS" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_REALTIMEREFLECTIONS" -d "$assets"/Mods "StandaloneLinux/realtime reflections.dfmod" 
    if [ "$TEXTURESXL" = "Y" ]; then
        echo "TEXTURESXL has REALTIMEREFLECTIONS textures already, skipping"
    else
        unzip "$SOURCEDIR/$ARC_REALTIMEREFLECTIONS" -d "$TEMP" RealtimeReflections_textures.zip
        unzip "$TEMP"/RealtimeReflections_textures.zip -d "$assets"/Textures
    fi
    echo "Mod: $ARC_REALTIMEREFLECTIONS" >> "$SIGNATUREFILE"
fi

if [ "$VILLAGERIMMERSION" = "Y" ]; then
    unrar x -y "$SOURCEDIR/$ARC_VILLAGERIMMERSION" "$assets"/Textures/
    echo "Mod: $ARC_VILLAGERIMMERSION" >> "$SIGNATUREFILE"
fi

if [ "$POSTPROCESSING" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_POSTPROCESSING" -d "$assets"/Mods "${ARC_POSTPROCESSING%.zip}"/Linux/postprocessing.dfmod
    echo "Mod: $ARC_POSTPROCESSING" >> "$SIGNATUREFILE"
fi

if [ "$CONVENIENTCLOCK" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_CONVENIENTCLOCK" -d "$assets"/Mods "StandaloneLinux/convenient clock.dfmod"
    # unzip "$SOURCEDIR/$ARC_CONVENIENTCLOCK" -d "$TEMP" "\[OPTIONAL\] TEXTURE OVERRIDE/*"
    # cp -rv "$TEMP/[OPTIONAL] TEXTURE OVERRIDE/StreamingAssets/Textures/Clock" "$assets"/Textures/
    echo "Mod: $ARC_CONVENIENTCLOCK" >> "$SIGNATUREFILE"
fi

if [ "$LOADINGSCREEN" = "Y" ]; then
    unzip "$SOURCEDIR/$ARC_LOADINGSCREEN" -d "$TEMP" "${ARC_LOADINGSCREEN%.zip}"/StreamingAssets/Mods/LoadingScreen/'*'
    mv -v "$TEMP/${ARC_LOADINGSCREEN%.zip}"/StreamingAssets/Mods/LoadingScreen "$assets"/Mods/
    unzip -j "$SOURCEDIR/$ARC_LOADINGSCREEN" -d "$assets"/Mods/LoadingScreen/ "${ARC_LOADINGSCREEN%.zip}"/OS-specific/Linux/loadingscreen.dfmod
    echo "Mod: $ARC_LOADINGSCREEN" >> "$SIGNATUREFILE"

    if [ "$LOADINGSCREENOBLIVION" = "Y" ]; then
	unrar x -y "$SOURCEDIR/$ARC_LOADINGSCREENOBLIVION" "$assets"/Mods/LoadingScreen/Images/
	echo "Mod: $ARC_LOADINGSCREENOBLIVION" >> "$SIGNATUREFILE"
    fi
fi

if [ "$READABLEBOOKS" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_READABLEBOOKS" -d "$assets"/Books/
    echo "Mod: $ARC_READABLEBOOKS" >> "$SIGNATUREFILE"
fi

# -- Sound

if [ "$MIDNIGHTPRINCESOUNDSCAPE" = "Y" ]; then
    unzip "$SOURCEDIR/$ARC_MIDNIGHTPRINCESOUNDSCAPE" -d "$assets"/
    echo "Mod: $ARC_MIDNIGHTPRINCESOUNDSCAPE" >> "$SIGNATUREFILE"
fi

if [ "$DFREMASTEREDMUSIC" = "Y" ]; then
    unrar x "$SOURCEDIR/$ARC_DFREMASTEREDMUSIC" "$assets"/Sound/
    echo "Mod: $ARC_DFREMASTEREDMUSIC" >> "$SIGNATUREFILE"
fi

if [ "$SOUNDCLIPSMIXDOWN" = "Y" ]; then
      mkdir -p "$assets"/Sound/
      unzip "$SOURCEDIR/$ARC_SOUNDCLIPSMIXDOWN" -d "$assets"/Sound/
      echo "Mod: $ARC_SOUNDCLIPSMIXDOWN" >> "$SIGNATUREFILE"
fi

# -- Gameplay

if [ "$TEDIOUSTRAVEL" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_TEDIOUSTRAVEL" -d "$assets"/Mods/ StandaloneLinux/tedioustravel.dfmod
    echo "Mod: $ARC_TEDIOUSTRAVEL" >> "$SIGNATUREFILE"
fi

if [ "$WARMASHES" = "Y" ]; then
    #unzip -j "$SOURCEDIR/$ARC_WARMASHES" -d "$assets"/QuestPacks/ Kamer/WarmAshes/WAQ00.txt
    unzip "$SOURCEDIR/$ARC_WARMASHES" -d "$assets"/Quests/ Kamer/WarmAshes/WAQ01.txt Kamer/WarmAshes/WAQ02.txt Kamer/WarmAshes/WAQ03.txt Kamer/WarmAshes/WAQ04.txt
    unzip "$SOURCEDIR/$WARMASHES_QUESTLIST" -d "$assets"/Quests/Kamer/WarmAshes/
    echo "Mod: $ARC_WARMASHES" >> "$SIGNATUREFILE"
fi

if [ "$QUESTPACK1" = "Y" ]; then
    unzip -o "$SOURCEDIR/$ARC_QUESTPACK1" -d "$assets"/QuestPacks # Should only unpack JH subdir & contents, oh well
    echo "Mod: $ARC_QUESTPACK1" >> "$SIGNATUREFILE"
fi
if [ "$QUESTPACK1PERPETUALS" = "Y" ]; then
    unzip -o "$SOURCEDIR/$ARC_QUESTPACK1PERPETUALS" -d "$assets"/QuestPacks
    echo "Mod: $ARC_QUESTPACK1PERPETUALS" >> "$SIGNATUREFILE"
fi

if [ "$ARCHEOLOGISTSGUILD" = "Y" ]; then
    unzip -j "$SOURCEDIR/$ARC_ARCHEOLOGISTSGUILD" -d "$assets"/Mods/ archaeologists.dfmod
    echo "Mod: $ARC_ARCHEOLOGISTSGUILD" >> "$SIGNATUREFILE"
fi

if [ "$PERSISTENTDUNGEONS" = "Y" ]; then
    cp "$SOURCEDIR/$ARC_PERSISTENTDUNGEONS" "$assets"/Mods/
    echo "Mod: $ARC_PERSISTENTDUNGEONS" >> "$SIGNATUREFILE"
fi

if [ "$USE_HACKS" = "Y" ]; then
forcesize () {
    echo "<?xml version=\"1.0\"?>
<info>
<width>$2</width>
<height>$3</height>
</info>" > "$assets/Textures/$1.xml"
}
    
    # https://forums.dfworkshop.net/viewtopic.php?f=27&t=1021&p=14696#p14696
    if [ "$CONVENIENTCLOCK" = "Y" ]; then
	# Not compatible with resized compasses, revert to original size
        forcesize Img/COMPASS.IMG 322 14
        forcesize Img/COMPBOX.IMG 69 17
    fi
fi

echo "Installation: successful" >> "$SIGNATUREFILE"
echo "Installed successfully under \`$TARGETDIR'"
exit 0
