#!/bin/bash

# Stop if anything goes wrong
set -e

self=$(basename "$0")

fatal() {
    echo "$self: $1" 1>&2
    exit 1
}

usage() {
    echo "Usage: $self [install directory]" 1>&2
    exit 1
}

mypath=$(dirname "$0")
mypath=$(cd "$mypath" && pwd)
[ -z "$mypath" ] && fatal "can't find my own directory"

check_available() {
    command -v "$1" > /dev/null 2>&1 || fatal "\`$1' command not found"
}

# Use 7z for everything?
check_available unzip
check_available unrar
check_available 7z

SOURCEDIR="$mypath"

TARGETDIR="$HOME/bin/daggerfall_unity"
[ -n "$1" ] && TARGETDIR="$1"

SIGNATUREFILE=.deploy_DFU
if [ -d "$TARGETDIR" ]; then
    [ -e "$TARGETDIR/$SIGNATUREFILE" ] || fatal "not replacing \`$TARGETDIR' we didn't create"
    rm -rf "$TARGETDIR"
fi
mkdir -p "$TARGETDIR"
touch "$TARGETDIR/$SIGNATUREFILE"

# --------------------------------------------------------------------

# By default this script will look for archives in its directory; Feel free to override
#SOURCEDIR="$HOME/Downloads/Daggerfall Unity"

# Base game https://www.dfworkshop.net/projects/daggerfall-unity/live-builds/
BASEGAME=interkarma-daggerfall-unity-daggerfallunity_linux_universal-127.zip

# Eye candy

# Daggerfall Remaster 3.0 https://forums.dfworkshop.net/viewtopic.php?f=27&t=1168
REMASTER30=Textures_3.0.rar
# Enhanced Sky https://forums.dfworkshop.net/viewtopic.php?f=14&t=29&start=50
ENHANCEDSKY=EnhancedSky_2.1.0.zip
# Distant Terrain https://forums.dfworkshop.net/viewtopic.php?f=27&t=10
DISTANTTERRAIN=DistantTerrain_2.4.1.zip
# Mountains and Hills https://forums.dfworkshop.net/viewtopic.php?f=27&t=1008
MOUNTAINSHILLS="Mountain And Hills 1.01.zip"
# Real Grass 2 https://forums.dfworkshop.net/viewtopic.php?f=27&t=964
REALGRASS=RealGrass_2.2.7z
# Vibrant Wind https://forums.dfworkshop.net/viewtopic.php?f=14&t=532
VIBRANTWIND=VibrantWind_v0.5_.7z
# Realtime Reflections https://forums.dfworkshop.net/viewtopic.php?f=27&t=122
REALTIMEREFLECTIONS=RealtimeReflections_2.2.0.zip
# Villager Immersion Overhaul https://forums.dfworkshop.net/viewtopic.php?f=27&t=924
VILLAGERIMMERSION=VIO-V2.rar
# Post Processing Effects https://forums.dfworkshop.net/viewtopic.php?f=27&t=694
POSTPROCESSING=PostProcessing_0.3.1a_.7z
# Convenient Clock https://forums.dfworkshop.net/viewtopic.php?f=27&t=1021
CONVENIENTCLOCK="Convenient Clock 1.02.zip"
# Loading Screen https://forums.dfworkshop.net/viewtopic.php?f=27&t=469
LOADINGSCREEN=LoadingScreen_2.2_.7z
LOADINGSCREENOBLIVION=OblivionStyledLoadScreensV2.rar

# Gameplay

# Warm Ashes: Dangerous Dungeon Exteriors https://forums.dfworkshop.net/viewtopic.php?f=27&t=1087
WARMASHES=WarmAshesV1.1.rar
# DFU Quest Pack #1 https://forums.dfworkshop.net/viewtopic.php?f=27&t=924
QUESTPACK1GUILD=Quest_Pack_1_Guild.zip
QUESTPACK1NONGUILD=Quest_Pack_1_NonGuild.1.zip
QUESTPACK1PERPETUALS="Quest Pack 1 Perpetuals.zip"

# --------------------------------------------------------------------

unzip "$SOURCEDIR/$BASEGAME" -d "$TARGETDIR"

# Mods https://forums.dfworkshop.net/viewforum.php?f=27

# -- Eye candy

if [ "$REMASTER30" ]; then
    unrar x "$SOURCEDIR/$REMASTER30" "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/
fi

if [ "$ENHANCEDSKY" ]; then
    unzip -j "$SOURCEDIR/$ENHANCEDSKY" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods "StandaloneLinux/enhanced sky.dfmod"
fi

if [ "$DISTANTTERRAIN" ]; then
    unzip -j "$SOURCEDIR/$DISTANTTERRAIN" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods "StandaloneLinux/distant terrain.dfmod"
fi

if [ "$MOUNTAINSHILLS" ]; then
    unzip -j "$SOURCEDIR/$MOUNTAINSHILLS" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods "StandaloneLinux/mountains and hills.dfmod"
fi

if [ "$REALGRASS" ]; then
    7z e "$SOURCEDIR/$REALGRASS" "${REALGRASS%.7z}"/Mod/Linux/realgrass.dfmod -o"$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods/
fi

if [ "$VIBRANTWIND" ]; then
    7z e "$SOURCEDIR/$VIBRANTWIND" "${VIBRANTWIND%.7z}"/Linux/vibrantwind.dfmod -o"$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods/
fi

if [ "$REALTIMEREFLECTIONS" ]; then
    unzip -j "$SOURCEDIR/$REALTIMEREFLECTIONS" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods "StandaloneLinux/realtime reflections.dfmod" 
    unzip -o "$SOURCEDIR/$REALTIMEREFLECTIONS" -d /tmp RealtimeReflections_textures.zip
    unzip /tmp/RealtimeReflections_textures.zip -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Textures
fi

if [ "$VILLAGERIMMERSION" ]; then
    unrar x -y "$SOURCEDIR/$VILLAGERIMMERSION" "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Textures/
fi

if [ "$POSTPROCESSING" ]; then
    7z e "$SOURCEDIR/$POSTPROCESSING" "${POSTPROCESSING%.7z}"/Linux/postprocessing.dfmod -o"$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods/
fi

if [ "$CONVENIENTCLOCK" ]; then
    unzip -j "$SOURCEDIR/$CONVENIENTCLOCK" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods "StandaloneLinux/convenient clock.dfmod"
fi

if [ "$LOADINGSCREEN" ]; then
    7z x "$SOURCEDIR/$LOADINGSCREEN" -o/tmp "${LOADINGSCREEN%.7z}"/StreamingAssets/Mods/LoadingScreen
    mv /tmp/"${LOADINGSCREEN%.7z}"/StreamingAssets/Mods/LoadingScreen "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods/
    7z e "$SOURCEDIR/$LOADINGSCREEN" -o"$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods/LoadingScreen/ "${LOADINGSCREEN%.7z}"/OS-specific/Linux/loadingscreen.dfmod

    if [ "$LOADINGSCREENOBLIVION" ]; then
	unrar x -y "$SOURCEDIR/$LOADINGSCREENOBLIVION" "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Mods/LoadingScreen/Images/
    fi
fi

# -- Gameplay

if [ "$WARMASHES" ]; then
    unrar x "$SOURCEDIR/$WARMASHES" -o "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/Quests/ WAQ01.txt WAQ02.txt WAQ03.txt WAQ04.txt
    unrar x "$SOURCEDIR/$WARMASHES" -o "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/QuestPacks/ WAQ00.txt
fi

if [ "$QUESTPACK1GUILD" ]; then
    unzip -o "$SOURCEDIR/$QUESTPACK1GUILD" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/QuestPacks # Should only unpack JH subdir & contents, oh well
fi
if [ "$QUESTPACK1NONGUILD" ]; then
    unzip -o "$SOURCEDIR/$QUESTPACK1NONGUILD" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/QuestPacks # Should only unpack JH subdir & contents, oh well
fi
if [ "$QUESTPACK1PERPETUALS" ]; then
    unzip -o "$SOURCEDIR/$QUESTPACK1PERPETUALS" -d "$TARGETDIR"/DaggerfallUnity_Data/StreamingAssets/QuestPacks
fi

echo "Installed successfully under \`$TARGETDIR'"
exit 0
